version: '3.8'
services:
  gateway:
    build: gateway/
    image: shareit-gateway-image
    container_name: shareit-gateway
    ports:
      - "8080:8080"
      - "5006:5006"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/
    image: shareit-server-image
    container_name: shareit-server
    ports:
      - "9090:9090"
      - "5005:5005"
    depends_on:
      - db

  db:
    image: postgres:13.7-alpine
    container_name: java-shareit
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shareit